###

POST http://localhost:8080/car
Content-Type: application/x-www-form-urlencoded

id=3&maker=Ford&model=Mondeo2&price=40001

###

POST http://localhost:8080/car
Content-Type: application/json

{"id": 331,
  "maker": "Ford",
  "model": "AMondeo",
  "price": 50000}

###

GET http://localhost:8080/car

###

PUT http://localhost:8080/car
Content-Type: application/json

{"id": 2,
  "maker": "Ford",
  "model": "Mondeo2",
  "price": 40002}

###

DELETE http://localhost:8080/car/624922a13575d24762176132

###

DELETE http://localhost:8080/car/2

###